name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build for macOS
      run: |
        GOOS=darwin GOARCH=amd64 TAGNAME=${{ github.ref_name }} ./scripts/build.sh

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 TAGNAME=${{ github.ref_name }} ./scripts/build.sh

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 TAGNAME=${{ github.ref_name }} ./scripts/build.sh

    - name: Create release
      run: |
        gh release create "${{ github.ref_name }}" \
          --repo="${{ github.repository }}" \
          --title="ATSA Notifier ${{ github.ref_name }}" \
          --generate-notes \
          "./output/atsa-notifier-${{ github.ref_name }}-darwin-amd64.zip" \
          "./output/atsa-notifier-${{ github.ref_name }}-windows-amd64.zip" \
          "./output/atsa-notifier-${{ github.ref_name }}-linux-amd64.tar.gz"
